
# Required
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"

# NB: this config is expected to fail at readthedocs; the "Exact" redirect configuration with wildcard should take
# care of the required redirects
